#!/bin/env bash

PWD=`pwd`
if [ "${PWD}" != "$HOME/git_project/bashlib_y" ];then
	echo "FATAL: Current directory is not '~/git_project/${PWD##*/}'."
	exit
fi

if [ -d /data/data/com.termux/files ];then
	R=/data/data/com.termux/files
	SUDO=
else
	R=
	SUDO="sudo"
fi

mkl(){
	if [ ! -e "$R$1/$f" -a ! -L "$R$1/$f" ];then
		$SUDO ln -vs "$PWD/$f" $R$1
	else
		echo " "$R$1/$f already exists.
	fi
}

for f in `ls`; do
	if [ -x ./$f ]; then
		mkl /usr/bin
	elif [ $f != README.md ]; then
		FL=`head -1 $f`
		if [[ $FL =~ ^\#[\ \t]*bash ]];then
			$SUDO mkdir -p /usr/share/bashlib_y
			mkl /usr/share/bashlib_y
		fi
	fi
done



