#!/bin/env bash

. gy_spport



for f in `ls`; do
	if [ -x ./$f ]; then
		install $f
	elif [ $f != README.md ]; then
		FL=`head -1 $f`
		if [[ $FL =~ ^\#[\ \t]*bash ]];then
			install $f /usr/share/bashlib_y
		fi
	fi
done





